### PR TITLE
Save fs button selected channel

### PR DESCRIPTION
**Pull request by mihero**
Save to last selected channel if channel selected with fs buttons.

Tested with fatshark

### CODE REVIEW

**Comment by piodabro** [comment]
Maybe its better to move setAndSaveChannel to Receiver namespace

**Comment by mihero** [comment]
architectural refactoring? move all eeprom handling out of ui code and inside specific modules.
At the same time introduce system module that would contain beeper, callsign,(button) high-level interface and eeprom storing?

**Comment by piodabro** [comment]
as you can see in code in this pull request, setting and saving channel is done in 3 or more places with almost the same code. I didnt followed DRY rule :)

**Comment by mihero** [comment]
yep, just meant that same kind of issue is in other parts as well. eeprom writing is mainly on ui code.
But I can clean the receiver part for now.

**Comment by piodabro** [comment]
Finally had some time to test changes ;)
Good job.
Merging...

**Pull request merged**
