### PR TITLE
modifiable callsing

### PR DESCRIPTION
**Pull request by mihero**
callsign editable in settings.
callsign visible on screensaver.

new icon for callsign settings
screensaver only shows callsign.

callsign is limited to 8char

### CODE REVIEW

**Comment by piodabro** [comment]
Thanks for your work. It look really good. But i have some remarks:
1. Callsign can be longer than 8 chars. i.e we have 128 pixels, one char of size 2 has 10pix width, so we can make it 10char long (EEPROM has 2kb of memory so it will be ok too ;) ).
2. In callsign settings, the border around each letter should be a little wider and higher - it sticks with some letters - add 1pix on top and 1 pix on left.
3. There is no default empty callsign (or the name of firmware). When i updated i saw $%^@%$ as a callsign ;).
4. Something wrong happens when scrolling down the letters in callsign settings.
5. Holding UP scrolls letters too fast.
6. Holding DOWN erases all letters?

There is some things to fix. Also i will update the project with new HAL drivers.
I will merge your changes now, but if you fix some things feel free to make new pull request.

**Comment by mihero** [comment]
1.) ok that is easy change
2.) drawing uses just inverted char draw, need to add rectangle draw there also
3.)default callsign is the value in CALLSIGN definition. should default val and compile flag be separated?
acting as a flag and content. 
4.) ??
5.) uses default button functionality, i can check if long press can be easily slowed down
6.) down goes thru chars and stops on 0 so it acts as a ending of callsign, so if you set it on first then it goes as 0 length, one option would be to not save if new callsign is zero length

**Comment by piodabro** [comment]
3. Default callsign can be set by macrodefinition with #ifndef, so you can set it in compile time ;)
4. When you scroll down sometimes all letters disappears.
5. You can use Timer class to count delays. Do not use delays.
6. So this is a little confusing. Also the big letters should be followed by small, and then other special signs.

**Comment by mihero** [comment]
4) it works as intended. when scrolling down it stops in the beginning on the loop and set 0 as end mark on that position
5) timer is added on #9 
6) it just goes thru ascii values in order

**Pull request merged**
