### PR TITLE
Update HAL+CMSIS, SSD1306 DMA Updates, Fix I2C_Reset

### PR DESCRIPTION
**Pull request by conkerkh**

### CODE REVIEW

**Comment by mihero** [comment]
on main.cpp 
156 I2C_Reset(hi2c2, MX_I2C2_Init);
doesn't compile on hb5808, missing &

**Comment by conkerkh** [comment]
Fixed, also sorted out buttons:P

**Comment by mihero** [comment]
tested on fatshark. works ok.

**Comment by piodabro** [comment]
I've made some HAL updates in local branch, now i do not have to publish them ;)

We have to make a flag that blocks drawing next frame until first is fully sent, or make double buffering.
Blocking with while -> NOP makes DMA sending work the same as synchronous I2C ;)

Checked, everything works, ready to merge ;)
Thanks.

**Comment by piodabro** [comment]
What does this means?
//I2C_Reset breaks stuff...
main.cpp line 151

**Pull request merged**
